import csv
from csvHeaders import playerInfoHeaders, playerMatchStatsHeaders, playerFplStatsHeaders

def writePlayerInfo(player, writer):
  writer.writerow(playerInfoHeaders)
  writer.writerow([
    player['id'],
    player['first_name'],
    player['second_name'],
    player['element_type'],
    player['team'],
    player['team_code'],
    player['news'],
    player['news_added'],
    player['squad_number'],
    player['web_name'],
    player['photo'],
    player['status'],
    player['code']
  ])

def writePlayerMatchStats(player, writer):
  writer.writerow(playerMatchStatsHeaders)
  writer.writerow([
    player['id'],
    player['first_name'],
    player['second_name'],
    player['team'],
    player['team_code'],
    player['minutes'],
    player['goals_scored'],
    player['assists'],
    player['clean_sheets'],
    player['goals_conceded'],
    player['own_goals'],
    player['penalties_saved'],
    player['penalties_missed'],
    player['yellow_cards'],
    player['red_cards'],
    player['saves'],
  ])

def writePlayerFplStats(player, writer):
  writer.writerow(playerFplStatsHeaders)
  writer.writerow([
    player['id'],
    player['first_name'],
    player['second_name'],
    player['team'],
    player['team_code'],
    player['element_type'],
    player['total_points'],
    player['event_points'],
    player['points_per_game'],
    player['form'],
    player['ep_this'],
    player['ep_next'],
    player['selected_by_percent'],
    player['now_cost'],
    player['cost_change_start'],
    player['cost_change_start_fall'],
    player['cost_change_event'],
    player['cost_change_event_fall'],
    player['value_form'],
    player['value_season'],
    player['transfers_in_event'],
    player['transfers_in'],
    player['transfers_out'],
    player['transfers_out_event'],
    player['in_dreamteam'],
    player['creativity'],
    player['special'],
    player['ict_index'],
    player['influence'],
    player['creativity_rank_type'],
    player['bonus'],
    player['chance_of_playing_next_round'],
    player['bps'],
    player['threat_rank_type'],
    player['ict_index_rank_type'],
    player['influence_rank'],
    player['threat'],
    player['creativity_rank'],
    player['chance_of_playing_this_round'],
    player['threat_rank'],
    player['ict_index_rank'],
    player['dreamteam_count'],
    player['influence_rank_type']
  ])
